---
- hosts: localhost
  tasks:
  - ec2:
      instance_type: t2.micro
      key_name: Bastion_IAAC
      region: us-east-1
      count: 1
      image: ami-0323c3dd2da7fb37d
      instance_tags:
        name: Created_by_ansible


      
